modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "runes_of_power"
version = "${version}"
displayName = "Runes of Power"
authors = "Bandit-bytes"
description = '''
Nine exciting Runes great for fantasy and RPG realms.
'''
#logoFile = ""

[[dependencies.runes_of_power]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.runes_of_power]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.runes_of_power]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "runes_of_power.mixins.json"
